### ISSUE TITLE
budgie support?

### ISSUE THREAD

**Issue by fossfreedom** [vinceliuice/matcha#1]
Hi there,

 I note the README says this theme supports budgie.  

However I don't see any budgie specific theming elements - mistake in the README?

The budgie elements I'm referring to is here:

 - https://github.com/budgie-desktop/budgie-desktop/tree/master/src/theme/3.20

**Comment by vinceliuice** [comment]
Sorry about that, I was planed to support budgie, but not yet now.

**Comment by vinceliuice** [comment]
Thanks anyway
