### ISSUE TITLE
WM icon problems of 3.3

### ISSUE THREAD

**Issue by wangxa** [vinceliuice/matcha#14]
I like this theme. After using the version 3.3, I found a problem of the icons in the window manager.

The first gif shows the problem of gnome-terminal. When mouse is hovering an icon, the corresponding grey icon disappear.
![peek 2018-01-20 14-40](https://user-images.githubusercontent.com/1250269/35184663-a1c0be34-fdf0-11e7-9e76-bec42ba23e05.gif)

The second is for gvim. When the gvim window is put at top, the icons disappear.
![peek 2018-01-20 14-41](https://user-images.githubusercontent.com/1250269/35184671-b1cdd8e8-fdf0-11e7-94c0-401502782e4c.gif)

To compare, I also upload the correct icons for Nautilus.
![peek 2018-01-20 14-43](https://user-images.githubusercontent.com/1250269/35184687-cbb52cac-fdf0-11e7-8d1e-8296b6a25cc7.gif)

**Comment by vinceliuice** [comment]
Is it just gvim and gnome-terminal have issues or all gtk softwares have those issues?

**Comment by wangxa** [comment]
Sublime Text 3, firefox 57, atom, LibreOffice, inkscape, gnome-search-tool, gimp, dia, visual studio code, ghex, glade3, audacious, and gucharmap also have the same problem as gvim.

**Comment by vinceliuice** [comment]
I upload the last version on github now! please reinstall matcha and try again. But The weird thing is matcha work well on my desktop(ubuntu17.10), I don't find those issues that you have.

**Comment by wangxa** [comment]
Thank you. I have tried the latest commit and they are fine. Now I realise that the problem is not in your github code but in that of gnome-look.org.. I downloaded the version 3.3 from gnome-look.org and that version gave such problems.

**Comment by vinceliuice** [comment]
Maybe there is something wrong with the version 3.3 from gnome-look.org that I upload, well I'll upload the new one on gnome-look.org. Thanks for your feedback.
