### ISSUE TITLE
Something wrong in Ubuntu 16.04

### ISSUE THREAD

**Issue by KangHuaLi** [vinceliuice/matcha#16]
Sorry to bother.
I try to install matcha theme in my destop. 
There's no error occuring during installation process.
However, the result is shown in below.
The left column is not as elegant as the readme show.
Moreover, the rows are too crowded and weird. 
![matcha](https://user-images.githubusercontent.com/25005776/37287531-f65e5966-263f-11e8-97d0-a39190517610.png)

On the contrary,
I also install the original Arc-theme,
and the result is excellent!
![arch](https://user-images.githubusercontent.com/25005776/37287420-c1541d32-263f-11e8-9e66-ec8feb7f7bdf.png)

Is there something wrong with the installation?
Or does the matcha not support for ubuntu 16.04?

**Comment by vinceliuice** [comment]
Sorry, matcha just support ubuntu16.10 or later

**Comment by KangHuaLi** [comment]
Ok, thanks!
Maybe I should update my Ubuntu version~

**Comment by vinceliuice** [comment]
Or you can just update you gtk version:
  sudo add-apt-repository ppa:gnome3-team/gnome3-staging
  sudo add-apt-repository ppa:gnome3-team/gnome3
  sudo apt-get update
  sudo apt-get dist-upgrade
