### ISSUE TITLE
Close button in Chrome is always big

### ISSUE THREAD

**Issue by morisrc** [vinceliuice/matcha#17]
Hi,
as the title says, the "close" button in Chrome is always big (like when the mouse goes over it).
This happen only with Chrome, I don't have the same issue with Chromium. 

![schermata da 2018-03-13 19-49-25](https://user-images.githubusercontent.com/20545323/37370292-0541df12-270c-11e8-9214-e2fd2a5b7b3b.png)

**Comment by vinceliuice** [comment]
Are you using the last version of Matcha? I already fixed this at last version

**Comment by morisrc** [comment]
You're right, sorry. I downloaded the latest version from Gnome-look, I think it is not updated. Now I have installed it via Github and it works.
Thanks so much!
