### ISSUE TITLE
[request] vala-panel + openbox & lxde menu bar

### ISSUE THREAD

**Issue by denikris** [vinceliuice/matcha#18]
![wm](https://user-images.githubusercontent.com/16707606/37470456-280b73a2-289a-11e8-9302-3fa8b99a2f9d.png)
different color of window and menubar in lubuntu 17.10

![2018-03-15-214931_1024x600_scrot](https://user-images.githubusercontent.com/16707606/37470927-391a7b42-289b-11e8-8f0f-5f66baabd8d1.png)
and there is panel from https://github.com/rilian-la-te/vala-panel, vala-panel also have icon task list based on budgie that seem not themed yet, adapta has theme for this panel

hope you can update it sooner or later for this great theme :-)

**Comment by vinceliuice** [comment]
Fixed now

**Comment by denikris** [comment]
![2018-03-16-020427_1024x600_scrot](https://user-images.githubusercontent.com/16707606/37485794-078604b0-28bf-11e8-91e0-7c0a8f5a2a87.png)
![2018-03-16-020552_1024x600_scrot](https://user-images.githubusercontent.com/16707606/37485800-0dc3da3c-28bf-11e8-9517-396a2d156ec2.png)


can you make it more readable like one is active window and other innactive window(s), please :-)

**Comment by vinceliuice** [comment]
Now fixed!
