### ISSUE TITLE
Double minimize button Firefox 60.0

### ISSUE THREAD

**Issue by Kibouo** [vinceliuice/matcha#19]
The latest Firefox Beta 60.0 has client-side gtk decorations. However, now it also shows a 'ghost' minimalization button as can be seen [here](https://i.imgur.com/b430Wn2.png) and [here](https://i.imgur.com/ZyHux4B.png). This doesn't appear anywhere else.

Could you please look into this? Love the theme!

Version info
Firefox: firefox-beta-bin 60.0b5-1
Firefox theme: default black
Murrine: gtk-engine-murrine 0.98.2-3
Gtk engines: gtk-engines 2.21.0-3
Gtk: gtk3 3.22.28-1
Gnome: 3.26.2
OS: Arch Linux x86_64

**Comment by vinceliuice** [comment]
Ok, I'll try fix this

**Comment by Kibouo** [comment]
It has been fixed in firefox-beta-bin 60.0b6-1.
