### ISSUE TITLE
Support for a modded version of arc-firefox-theme

### ISSUE THREAD

**Issue by hThoreau** [vinceliuice/matcha#2]
Good evening,

Taking into account that your theme was based on the "Arc" theme, are there plans to implement a modded version, or instructions for the modification of, the arc-firefox-theme in order for it to fit in to the color scheme of matcha?

Thanks!

**Comment by vinceliuice** [comment]
Firefox is going to change the appearance and theme now， so maybe arc-firefox-theme will not support then， so I don‘t have plans for now， sorry about this.
