### ISSUE TITLE
Annoying blurred line over maximized windows

### ISSUE THREAD

**Issue by nplezka** [vinceliuice/matcha#22]
![schermata da 2018-05-03 17-28-14](https://user-images.githubusercontent.com/10550382/39586691-f8906b62-4ef7-11e8-8ea5-965518ffe1df.png)

**Comment by vinceliuice** [comment]
Can you tell me your gnome-shell theme?

**Comment by nplezka** [comment]
Oh, I forgot: It the Matcha-aliz one.

**Comment by vinceliuice** [comment]
I found the reason now, because Ubuntu changed the gnome-shell's maximized display effect, so that the topbar is no longer transparent when maximized, and my gnome-shell theme has a shadow under topbar, so the shadow becomes opaque when maximized, anyway, I will fix this issue.
