### ISSUE TITLE
How to install theme for Flatpak apps?

### ISSUE THREAD

**Issue by rauldipeas** [vinceliuice/matcha#26]
It's possible?

**Comment by vinceliuice** [comment]
I will try to upload this theme on flathub

**Comment by hThoreau** [comment]
Please do. :wink:

**Comment by hThoreau** [comment]
Any development in this front? Maybe the [arc theme available at flathub](https://github.com/flathub/org.gtk.Gtk3theme.Arc) can be used as reference?

**Comment by F3l1XQu1ll** [comment]
Please consider to upload it to Flathup, since it's the default theme on Manjaro, Flatpak apps are "broken" (using the default Gnome Adwaita theme instead of Matcha).

**Comment by F3l1XQu1ll** [comment]
I have build the necessary files to publish the package for flatpak - to create a flatpak repository to install the theme in other words. Currently I made this for the dark-sea variant. The rest work is in progress. If you want to have a look on it: https://gitlab.com/F3l1XQu1ll/org.gtk.gtk3theme.matcha
@vinceliuice I would prefer to upload the stuff to Flathub (when ready) before creating my own repository on gitlab or github. But I don't want to do this without your permission.

**Comment by vinceliuice** [comment]
I've already upload one: https://github.com/flathub/org.gtk.Gtk3theme.Matcha-sea
It's ready to download now

**Comment by F3l1XQu1ll** [comment]
Ah, nice! 
You can tell me if you want help with the other versions.

**Comment by vinceliuice** [comment]
Thanks! @F3l1XQu1ll
I never used flathub before, if I get problem about flathub, I'll ask for your help! thanks for your job, I think I can use your file to build the dark version.

**Comment by hThoreau** [comment]
> I have build the necessary files to publish the package for flatpak - to create a flatpak repository to install the theme in other words. Currently I made this for the dark-sea variant. The rest work is in progress. If you want to have a look on it: https://gitlab.com/F3l1XQu1ll/org.gtk.gtk3theme.matcha
> @vinceliuice I would prefer to upload the stuff to Flathub (when ready) before creating my own repository on gitlab or github. But I don't want to do this without your permission.

Please make other versions of matcha available through flatpak, or at least this one.

**Comment by pheidippides** [comment]
Hi @vinceliuice,
Thanks a lot for the very nice theme, especially the dark variant, it's by far my preferred one! The drawback is that I'm totally dependent on it now :-)
I'm trying to transition some apps from my distro package manager to flatpak and my issue that I can have the light theme version to work by doing `flatpak install flathub org.gtk.Gtk3theme.Matcha-sea` but not the dark version. Could you also package the dark version and push it to flathub (I think this is also @hThoreau's request)? That would be really awesome.
Cheers.

**Comment by vinceliuice** [comment]
No problem!

**Comment by pheidippides** [comment]
> No problem!

That's really great, thanks a lot!

**Comment by pheidippides** [comment]
> No problem!

Hi @vinceliuice 
Do you have any news on this? I'd be happy to give it a try but I have no clue how to proceed ...

**Comment by jawadalkassim** [comment]
I'm using Manjaro when i use Matcha Dark azul for Application Theme Flatpak don't use the same theme, even if i install the theme manually as a flatpak theme with : `flatpak install flathub org.gtk.Gtk3theme.Arc-Dark`

**Comment by musfay** [comment]
@jawadalkassim As its described [here](https://docs.flatpak.org/en/latest/desktop-integration.html#theming), you need to install system default theme on flatpak.  ´´´flatpak install flathub org.gtk.Gtk3theme.Matcha-dark-azul´´´

**Comment by jawadalkassim** [comment]
@musfay Already installed, Actually  if i chose another theme like Arc or Materia flatpaks will automatically change the theme, except Matcha-theme  although I've installed the theme but all apps switched to adwaita Light
![image](https://user-images.githubusercontent.com/48631694/117156435-4b43fd00-ad83-11eb-8cea-e456326b7b33.png)

**Comment by musfay** [comment]
@jawadalkassim I tried to reproduce this issue on NixOS. Actually the problem is caused by the flatpak package as it's outdated and still linked to old SDK version 19.08. Other matcha variants works fine. [org.gtk.Gtk3theme.Matcha-dark-azul.json](https://raw.githubusercontent.com/flathub/org.gtk.Gtk3theme.Matcha-dark-azul/master/org.gtk.Gtk3theme.Matcha-dark-azul.json) 
There is a [PR](https://github.com/flathub/org.gtk.Gtk3theme.Matcha-dark-azul/pull/2) for it.

**Comment by jawadalkassim** [comment]
@musfay thanks for looking into this issue

**Comment by jawadalkassim** [comment]
@musfay can I modify it manually to fix this?  Or should I wait until it will be merged

**Comment by musfay** [comment]
@jawadalkassim You can edit all flatpak packages for your liking. [This](https://docs.flatpak.org/de/latest/first-build.html) documentation will help you. You just need to change SDK version and update the theme. You can also cherry-pick [this PR](https://github.com/flathub/org.gtk.Gtk3theme.Matcha-dark-azul/pull/2).

**Comment by jawadalkassim** [comment]
@musfay  I've compiled the theme locally with PR changes, but  nothing changed 
![image](https://user-images.githubusercontent.com/48631694/118497133-6818f280-b6ea-11eb-8a4e-86dcebfbea95.png)
![image](https://user-images.githubusercontent.com/48631694/118497256-85e65780-b6ea-11eb-9feb-12397c0622e8.png)

This is how flatpak apps looks like:
![image](https://user-images.githubusercontent.com/48631694/118497458-b62df600-b6ea-11eb-9c46-21329f8ba6a1.png),


steps:
```
mkdir app repo
flatpak-builder --ccache --repo=repo --subject="Build of Matcha-dark-azul `17/5/2021`" app org.gtk.Gtk3theme.Matcha-dark-azul.json
flatpak remote-add Matcha-dark-azul repo --no-gpg-verify
sudo flatpak install Matcha-dark-azul org.gtk.Gtk3theme.Matcha-dark-azul

```
And before that I've changed  `org.gtk.Gtk3theme.Matcha-dark-azul.json` as the PR explained
