### ISSUE TITLE
Broken boundaries problem

### ISSUE THREAD

**Issue by sandobits** [vinceliuice/matcha#27]
I'm trying to install the matcha themes but I keep getting this problem:
![screenshot_2018-05-28_16-37-00](https://user-images.githubusercontent.com/31490653/40627485-a678ebea-6295-11e8-984c-4bc0f5597d24.png)
It does not seem to affect any other themes I installed and I have tried updating the gtk engines as you mention in the description.
I'm running XFCE4 with Openbox WM.

**Comment by vinceliuice** [comment]
gnome version must > 3.20
