### ISSUE TITLE
Matcha is a totally different shade of green

### ISSUE THREAD

**Issue by jdamboeck** [vinceliuice/matcha#30]
And i would prefer a real matcha-version of matcha

![matcha_schale-und-besen-726x408](https://user-images.githubusercontent.com/20957463/45160974-0ee32c00-b1eb-11e8-90ba-c458641bd86e.jpg)
![matcha1](https://user-images.githubusercontent.com/20957463/45160976-0ee32c00-b1eb-11e8-86b5-47cf8c23a9ea.jpeg)

**Comment by vinceliuice** [comment]
Thanks, I'll consider add this color version to Matcha
