### ISSUE TITLE
Matcha sliders are wrong color in GNOME 3.30

### ISSUE THREAD

**Issue by aulospl** [vinceliuice/matcha#32]
Sliders are the default adwaita blue when using the theme in GNOME 3.30. Everything else seems to be right.
EDIT: I used the Matcha-dark-sea to take the screenshot, but other variants have the same issue.
![matcha_color](https://user-images.githubusercontent.com/12572896/45693474-95750300-bb33-11e8-867b-6fafc2202fb1.png)

**Comment by aulospl** [comment]
The issue seems to be due to GNOME using '-barlevel' attribute for sliders in 3.30. The OSD sliders are also affected.

**Comment by vinceliuice** [comment]
Thanks man! I'll fix this

**Comment by vinceliuice** [comment]
Fixed now!
