### ISSUE TITLE
Bug in pixman

### ISSUE THREAD

**Issue by Ste74** [vinceliuice/matcha#33]
Hi there,
i have installed this theme for testing purpose in our system. We have included in our repo ( Manjaro Linux ). At the moment in my daily runner gnome pc i have notice of this error:
```
(gnome-tweaks:3949): Gtk-WARNING **: 18:51:00.071: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node arrow, owner GtkTreeMenu)
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```
I see this example in a drop-down menu in gnome-tweak. 

Anyway is a great theme and also the sea version match with our [official color](https://www.colorhexa.com/16a085)

Cheers 
Stefano Capitani
Manjaro Linux

**Comment by ceyhunnabiyev** [comment]
Hi @vinceliuice , Manjaro Team want  to make matcha gtk theme as default theme. Please help them to solve such kind of problems.

**Comment by vinceliuice** [comment]
I have installed manjaro on my computer, I'll try fix this issue!

**Comment by Ste74** [comment]
@vinceliuice what Gnome Iso you installed ? In other word check the version of gnome-shell. If you downloaded the 17.1.12 this contain the gnome-shell 3.28.x but you need [beta 4](https://osdn.net/projects/manjaro/storage/gnome/18.0-beta4/) to test it after a full upgrade. In this way you have gnome-shell 3.30.1 and gtk 3.24 .. 
I have build just now arc-theme (NicoHood repo) with last commit and all work as expected

**Comment by vinceliuice** [comment]
Thanks @Ste74 I'll download this one and test again

**Comment by Ste74** [comment]
Sorry forgot to close this since the normal flow of update solve this
