### ISSUE TITLE
Icon selection color still blue on XFCE desktop icons (GTK3)

### ISSUE THREAD

**Issue by philmmanjaro** [vinceliuice/matcha#35]
Currently we are trying the **Matcha** theme to become the default theme of **Manjaro 18.0**. During our testing with XFCE 4.13 patches we found some issues with the desktop icons:

![blue](https://user-images.githubusercontent.com/5050022/46569568-5f1eec80-c957-11e8-9a40-037733946b13.jpg)

The selection color is in all themes still blue. At least for **Matcha-sea** I expected it to be highlighted in green.

**Comment by vinceliuice** [comment]
I‘ll fix this

**Comment by vinceliuice** [comment]
It's fixed now!
