### ISSUE TITLE
Hover introduced flickering in Thunar and Pamac

### ISSUE THREAD

**Issue by philmmanjaro** [vinceliuice/matcha#36]
Seems with b806581a48139780d5d4b8de94218279e3286c80 a mouse hover got introduced. This creates flickering with **gtk 3.24**. See also the video: [hover-flicker.zip](https://github.com/vinceliuice/matcha/files/2458165/hover-flicker.zip)

**Comment by vinceliuice** [comment]
This should be a bug in the Thunar， because all theme have this issue when you set view hover background color. so I removed view hover background color now. I can just wish Xfce4 can fix this bug at Thunar.

**Comment by philmmanjaro** [comment]
Well, it might have to do with **gtk 3.24**. If you downgrade that package to **gtk 3.22** it works. I don't know if the issue is only outside of **Gnome**. https://forum.manjaro.org/t/gtk-3-3-24-tooltip-flickering/58767

**Comment by philmmanjaro** [comment]
We can keep this issue open, until upstream provides the fix.

**Comment by vinceliuice** [comment]
Yes! I'll keep this open until upstream provides the fix.

**Comment by philmmanjaro** [comment]
@vinceliuice: seems one of the latest commits re-introduced the flickering.

**Comment by philmmanjaro** [comment]
Seems it is fixed now at [upstream](https://gitlab.gnome.org/GNOME/gtk/merge_requests/374). Most likely it will be in v3.24.2 **gtk3** package.

**Comment by philmmanjaro** [comment]
**3.24.1+33+g615fa7cfb6-0** of **gtk3** fixes the flickering. You can now reapply the hover effect @vinceliuice

**Comment by vinceliuice** [comment]
Removed now
