### ISSUE TITLE
Nemo File Manager primary bar is white.

### ISSUE THREAD

**Issue by Vencorr** [vinceliuice/matcha#4]
![home_003](https://user-images.githubusercontent.com/23224476/30462998-df925072-998e-11e7-9a70-bf7ff9b94de0.png)
It appears that a recent update has broken Nemo and it's fine black primary bar.

Currently using Cinnamon on Fedora 26, though I am not sure that matters.
Thought I would let you know.

**Comment by vinceliuice** [comment]
Sorry, I'll fix this

**Comment by vinceliuice** [comment]
Fixed now!
