### ISSUE TITLE
Same openbox themes

### ISSUE THREAD

**Issue by obi-juan88** [vinceliuice/matcha#40]
All openbox themes are the same, they all have Matcha-dark-sea colors.

**Comment by cr6git** [comment]
The last time I asked @vinceliuice to change [something](https://github.com/vinceliuice/matcha/issues/21), he simply closed my issue without responding...
:confused:

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now
