### ISSUE TITLE
Menu text very very dark in some apps (gtk2?)

### ISSUE THREAD

**Issue by kmansoft** [vinceliuice/matcha#42]
Fedora 29
XFCE
gtk2 2.24.32
gtk3 3.24.1

In GTK2 apps (claws mail, ristretto) the menu bar has very very dark text color, almost black, pretty much invisible against menu bar background which is also dark.

In GTK3 apps (xfce terminal, thunar) it's OK.

![matcha-claws-mail-menu-text](https://user-images.githubusercontent.com/1686219/47815757-52c55e00-dd62-11e8-927d-829b89730cf8.png)

Oh and where could I fix it myself in my own local copy, please?

**Comment by kmansoft** [comment]
It looks like same color

`gtk-color-scheme = "menu_fg: #263033"`

is used for:

- Text color of top level menus - really dark background
- Text color of second level menus (e.g. File or Edit) - almost white background
- Text color of popup (context, right mouse click) menus - almost white background

**Comment by vinceliuice** [comment]
![2018-11-01 10-15-37](https://user-images.githubusercontent.com/7604295/47828750-5affb680-ddbf-11e8-8846-0d425d2d5522.png)
I don't have this issue

**Comment by vinceliuice** [comment]
If you want to change menubar fg colors, you should check menubar-toolbar.rc, I used tooltip_fg_color not "menu_fg
