### ISSUE TITLE
Cinnamon window title box spacing

### ISSUE THREAD

**Issue by phpony** [vinceliuice/matcha#44]
Hi @vinceliuice and thanks for all the great work developing this theme!

As I see, when you work with cinnamon you prefer a label-less windows list, so you probably never saw how ugly it looks with labels. There's no spacing between window icon and window title with your current cinnamon.css.

This little snippet will fix the issue:
```
.window-list-item-box StLabel {
  padding-left: 5px;
}
```

Also I'd recommend to change .window-list-item-box font-weight from bold to normal. 
```
.window-list-item-box {
  font-weight: normal;
  ...
}
```

Just compare this screenshots:

- before:
![Before](https://i.imgur.com/M0vNtRV.png)

- after:
![After](https://i.imgur.com/3dlMH6X.png)

Can create a pull request if you're interested.

**Comment by vinceliuice** [comment]
Fixed now
