### ISSUE TITLE
Menubar invisible in some Applications

### ISSUE THREAD

**Issue by r0bc94** [vinceliuice/matcha#45]
In some applications, the Menubar buttons are invisible. 

It seems that the only affected applications are Electron based (but I'm not sure about typora).

![screenshot from 2018-12-01 16-01-35](https://user-images.githubusercontent.com/9255088/49329649-845c5f80-f582-11e8-9e04-a24abf1410f7.png)

**Comment by vinceliuice** [comment]
All Chromium based apps have this issue, I can only change Chromium menu style to fix this

**Comment by vinceliuice** [comment]
Fixed now
