### ISSUE TITLE
Icon Color Inconsistency

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [vinceliuice/matcha#47]
On Xubuntu 18.04 with XFCE after the newest update via the PPA the volume icon appears to be not quite white. It's close but it doesn't quite fit in with the rest of the icons in my system tray, it's like a grey colour instead of white.

The same has happened for the back, refresh, options buttons and the titles for a page in Chrome. 

Any chance for a fix please devs? And thanks for the awesome work

![screenshot_2018-12-21_16-59-47](https://user-images.githubusercontent.com/7698035/50354008-f1d82c00-0541-11e9-973b-b5af88f98f55.png)

![screenshot_2018-12-21_16-59-59](https://user-images.githubusercontent.com/7698035/50354014-f56bb300-0541-11e9-8014-c940335363d7.png)

**Comment by vinceliuice** [comment]
I make the panel fg_color lighter now
