### ISSUE TITLE
Beautiful theme, but matching the Shell screenshots (Dock and panel)

### ISSUE THREAD

**Issue by bit-less** [vinceliuice/matcha#48]
This is the most beautiful UI I've ever seen, by the way!

I installed the sea theme, but only the explorer windows and icons have the theme.  Even when I got the gnome theme extension, I only saw some of the top panel change styling.

What I want, is exactly what I see in your screenshots where the dock is on the bottom with the panel included (and to the right), and all the launcher app icons have a nicer look too.  Currently my dock is essentially identical as the default 18.04.1 and my panel is still at the top, but does look a little nicer.

I want my dock and panel to be merged and styled exactly like you have it in this screenshot, with the improved launcher app icons in the dock.  Is that part of this repo or pieces of other packages your using, and if that's the case, what are they?

Cheers!

Yours:
![2726958fde42a661fd7c0ffd581c3020a5d1](https://user-images.githubusercontent.com/33101456/50370248-94070c80-0560-11e9-90ed-e18e8e605eff.jpg)

Mine:
![screenshot from 2018-12-21 20-44-24](https://user-images.githubusercontent.com/33101456/50370296-7ab29000-0561-11e9-9b7c-37eabf054092.png)

**Comment by vinceliuice** [comment]
Then I think that's the gnome-shell-extension you need: [dash-to-panel](https://extensions.gnome.org/extension/1160/dash-to-panel/)

**Comment by bit-less** [comment]
Thanks!
