### ISSUE TITLE
GTK 2 & 3 Inconsistency

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [vinceliuice/matcha#49]
The right click menu for GTK 2 apps is lighter than the one in GTK apps (and in my opinion doesn't look as nice as the GTK 3 apps).

![screenshot_2018-12-22_05-32-31](https://user-images.githubusercontent.com/7698035/50371040-10264200-05ab-11e9-922f-7e1012299ef6.png)

![screenshot_2018-12-22_05-31-56](https://user-images.githubusercontent.com/7698035/50371045-2207e500-05ab-11e9-816f-de84f652c788.png)

**Comment by vinceliuice** [comment]
Didn't notice that before, I'll make it the same color

**Comment by vinceliuice** [comment]
Fixed now!
