### ISSUE TITLE
Workspace Layout Switcher cannot be distinguised if there are no open windows in workspace

### ISSUE THREAD

**Issue by siyia2** [vinceliuice/matcha#50]
In xfce4 when used with any matcha dark theme the workspace indicator is completely black wether it is selected or not, unless open windows are present in selected workspace it is very hard to figure out which workspace you are in:

![how_it_is](https://user-images.githubusercontent.com/46220960/50514868-b42b5400-0aa9-11e9-8f4b-c896ad49c4f9.png)

how it should be:

![how_it_should_be](https://user-images.githubusercontent.com/46220960/50514872-b8577180-0aa9-11e9-9485-46d9484850bd.png)

**Comment by siyia2** [comment]
You can also change the active indicator color to suit the theme's name f.e use dark sea color for active workspace instead of gray if matcha-dark-sea is selected in the theme options.

**Comment by vinceliuice** [comment]
I changed the workspace theme style, you can download the last update

**Comment by siyia2** [comment]
the latest git version includes the change?

**Comment by siyia2** [comment]
much better thanks

**Comment by vinceliuice** [comment]
You are welcome!
