### ISSUE TITLE
White inner border in Gnome Terminal

### ISSUE THREAD

**Issue by r0bc94** [vinceliuice/matcha#52]
Hey, since a recent update, some Applications such as the Gnome Terminal display a  1px white inner border. 

See: 
![screenshot from 2019-01-19 17-37-51](https://user-images.githubusercontent.com/9255088/51429670-2575a700-1c11-11e9-8ef3-409056839a6d.png)

This only happens when using a Light theme from the matcha collection. Dark themes doen't seem to be affected by this issue.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now, you can download the new push here

**Comment by r0bc94** [comment]
Awesome, thank you :smile:
