### ISSUE TITLE
Application title bar could use a bit more padding

### ISSUE THREAD

**Issue by asegarra** [vinceliuice/matcha#56]
Hi, don't know if this is by design but the title bar in apps like gnome-terminal when you disable the menu bar, the title bar looks quite thin, gnome settings looks like there's more padding and looks better, I suspect its due to client side decorations. Can upload screenshots
![Screenshot from 2019-03-21 21-25-05](https://user-images.githubusercontent.com/12531275/54794817-d56e8d00-4c1f-11e9-86a6-d943f702e126.png)

**Comment by vinceliuice** [comment]
Because this is not CSD titlebar, it's default-decoration titlebar. if I set the same size as CSD titlebar, it'll looks not good at other app with default-decoration titlebar.
