### ISSUE TITLE
Text is difficult to read in Cinnamon notifications

### ISSUE THREAD

**Issue by Janne-d-Arc** [vinceliuice/matcha#57]
The text and background in notifications are dark, making the text difficult to read.
![Matcha](https://user-images.githubusercontent.com/13596575/54892111-def13280-4e75-11e9-8d35-c901f4899c24.png)
Can you fix this, please?

**Comment by vinceliuice** [comment]
No problem I'll fix it

**Comment by Janne-d-Arc** [comment]
> No problem I'll fix it

Thank you!

**Comment by Janne-d-Arc** [comment]
Also, I don't know if I should report it as another issue but I think the "Run Dialog" (Alt+F2) doesn't look like it should:
![Matcha](https://user-images.githubusercontent.com/13596575/54950549-21af1b00-4f07-11e9-953b-0adfabadd602.png)

**Comment by vinceliuice** [comment]
Fixed now!
