### ISSUE TITLE
Chromium autofill popup bug

### ISSUE THREAD

**Issue by uzvermode** [vinceliuice/matcha#58]
OS: ```Archlinux```
matcha-gtk-theme-git: ```r200.1fd145e-1```
chromium: ```73.0.3683.103-1```
![matcha_bug_1](https://user-images.githubusercontent.com/1315398/55681856-faf3da00-5933-11e9-9beb-9f336b624549.png)

![matcha_bug_2](https://user-images.githubusercontent.com/1315398/55681858-00512480-5934-11e9-87ee-a54726a9a15e.png)

![matcha_bug_3](https://user-images.githubusercontent.com/1315398/55681859-047d4200-5934-11e9-8ff6-73917251f811.png)
Fix example [Fixed chrome issues](https://github.com/vinceliuice/Qogir-theme/commit/73ebba65e70d4f64451b947def72cf81cbd94468)

**Comment by vinceliuice** [comment]
I'll fix this soon

**Comment by vinceliuice** [comment]
Fixed now!
