### ISSUE TITLE
Not all variants available on gnome-shell

### ISSUE THREAD

**Issue by jeroni** [vinceliuice/matcha#59]
It seems not all theme variants are available for gnome-shell, only Matcha-sea and Matcha-dark-sea are installed via the Install executable.

![Captura de pantalla de 2019-04-09 11-52-02](https://user-images.githubusercontent.com/9005992/55791048-f5c29680-5abd-11e9-89b4-214fb230cd5d.png)

it seems intentional as there's an "if" condition on "sea" variant.

**Comment by vinceliuice** [comment]
Yes, because other color shell versions are not ready yet,  I will upload it when I am modified.

**Comment by vinceliuice** [comment]
Now! it's ok
