### ISSUE TITLE
Problem with Cinnamon 3.4

### ISSUE THREAD

**Issue by Dreknar** [vinceliuice/matcha#6]
Hey.
I found a problem with "control elements" in Cinnamon theme (version 3.4.6). Look at screen.
![bug](https://user-images.githubusercontent.com/24864886/31114082-a4b0c9e2-a81c-11e7-94e7-93c638701c67.png)

Can you resolve this in future. I like this theme so much, but can't used on Cinnamon. :/

**Comment by vinceliuice** [comment]
Matcha only support gtk3.20 or later desktops, If you want to use it, please update your gtk base (gnome) version:
sudo add-apt-repository ppa:gnome3-team/gnome3-staging
sudo add-apt-repository ppa:gnome3-team/gnome3
sudo apt-get update
sudo apt-get dist-upgrade
