### ISSUE TITLE
Weird Boxes In Whisker Menu

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [vinceliuice/matcha#61]
So the distro is Xubuntu 19.04
environment is XFCE,
latest matcha from git.

Screenshot of the issue: 
![Screenshot_2019-04-21_01-06-28](https://user-images.githubusercontent.com/7698035/56463934-38497480-63d6-11e9-86bc-b13a3f318906.png)

Screenshot of how it looked without the issue on a previous version:
![Screenshot_2019-04-21_01-39-38](https://user-images.githubusercontent.com/7698035/56463941-58793380-63d6-11e9-89d1-aad3785b0f3e.png)

**Comment by vinceliuice** [comment]
Fixed now
