### ISSUE TITLE
Matcha Volume and Brightness icons not centered

### ISSUE THREAD

**Issue by VernonSV** [vinceliuice/matcha#62]
Linux Mint 19.1 Tessa
Cinnamon 4.0.10
Intel© Celeron© CPU N2840 @ 2.16GHz × 2 & Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display

The issue happens on both dark sea and dark blue themes (those are the only ones that I've installed). Also the Software sources panel looks white. I've runned the command ' sudo ln -s ~/.themes/* /usr/share/themes/ ' so the themes apply globally since Synaptic and the Software sources panel runs as root, but this theme doesn't apply as you can see. Also a dev that gives support for Cinnamon 4 on the Adapta-Nokto theme told me that the volume icon not being centered was because of the Media Key OSD (On Screen Display) or something like that. So I don't know if that helps. Thanks anyway!
![Captura de pantalla de 2019-04-21 00-18-00](https://user-images.githubusercontent.com/43186467/56465841-b56fec00-63cc-11e9-9958-4ee5871dce73.png)
![Captura de pantalla de 2019-04-21 00-18-09](https://user-images.githubusercontent.com/43186467/56465842-bd2f9080-63cc-11e9-809f-4206229aed4d.png)
![Captura de pantalla de 2019-04-21 00-18-34](https://user-images.githubusercontent.com/43186467/56465844-c3be0800-63cc-11e9-9a00-7092bbf45a7f.png)

**Comment by vinceliuice** [comment]
OSD issue fixed now

**Comment by vinceliuice** [comment]
About the Software sources panel, you can check this app is snap/flathub version or not, because snap/flathub apps don't use system or user theme directory

**Comment by VernonSV** [comment]
Okay, will do tomorrow. Thanks for taking your time to read me and for your work.

**Comment by vinceliuice** [comment]
You are welcome!
