### ISSUE TITLE
Possible issue in gkt2.0 apps.rc file

### ISSUE THREAD

**Issue by GermanG** [vinceliuice/matcha#64]
I had an error running gksu 
/usr/share/themes/Matcha-dark-sea/gtk-2.0/apps.rc:14: Invalid color constant '@tooltip_fg_color'
/usr/share/themes/Matcha-dark-sea/gtk-2.0/apps.rc:14: error: invalid string constant "@tooltip_fg_color", expected valid string constant

If I remove the double quotes from https://github.com/vinceliuice/matcha/blob/9996184a759352ec886ee0ee7222488e1a538e31/src/gtk-2.0/apps.rc#L14 seems solved.

Tried to search for this issue in google but no results so far, that's why I ended up reporting it, sorry if this is not an issue.

Regards,
German

**Comment by vinceliuice** [comment]
Thanks! Didn't notice that this really can't have double quotes, I'll remove it
