### ISSUE TITLE
Styling inputs in Firefox

### ISSUE THREAD

**Issue by realcgslav** [vinceliuice/matcha#67]
Some websites are styling their `<input>` fields only by changing text color and not background. Because of this in Firefox (using dark theme) it's impossible to see text inside input field.

This is not present in webkit based browser.

Is there possibility to exclude from theme styling for inputs, textareas, buttons, checkboxes etc. in Firefox?

**Comment by vinceliuice** [comment]
Sorry to tell you gtk theme can not overwrite websites styling on firefox, you can go to about:config. Create a pref called widget.content.gtk-theme-override of type String, and give it a value of "Matcha". This will fix most web pages.

**Comment by realcgslav** [comment]
@vinceliuice the problem is that it is styling without turning any flags! Please read my issue again.

It is styling not styled by css inputs. So if website has style for font color to something dark, and input background is dark from the theme, you can't see anything in it.

**Comment by vinceliuice** [comment]
But firefox don't fully support gtk themes, I really don't konw how to control all firefox input style by gtk css file, the only solution I have is change about:config of firefox

**Comment by vinceliuice** [comment]
But firefox don't fully support gtk themes, I really don't konw how to control all firefox input style by gtk css file, the only solution I have is change about:config of firefox

**Comment by realcgslav** [comment]
Ok, we clearly do not understand each other. I'll explain by examples from my [CodePen](https://codepen.io/cgslav/full/eavpBW):

1. Matcha-**dark**-aliz and **Firefox**:

![1](https://user-images.githubusercontent.com/10274278/57797074-e7fdd200-7749-11e9-9b54-48c0a3bc9105.png)

2. Matcha-aliz and **Firefox**:

![2](https://user-images.githubusercontent.com/10274278/57797091-f6e48480-7749-11e9-94d2-7cd76e57534c.png)

3. Matcha-**dark**-aliz and **Vivaldi** (same for Chromium):

![3](https://user-images.githubusercontent.com/10274278/57797380-9bff5d00-774a-11e9-9714-edb9c9b98f8a.png)

4. Matcha-**dark-**aliz side by side **Firefox** and **Vivaldi** at once: 

![5](https://user-images.githubusercontent.com/10274278/57797411-ade10000-774a-11e9-87b9-719daecd63ba.png)

To test it by yourself, open my [CodePen](https://codepen.io/cgslav/full/eavpBW) in Firefox and switch between dark/light matcha theme.

**Comment by vinceliuice** [comment]
![2019-05-16 14-06-27 的屏幕截图](https://user-images.githubusercontent.com/7604295/57830786-cb16dc80-77e5-11e9-81e9-ece661070517.png)
go to about:config. Create a pref called widget.content.gtk-theme-override of type String, and give it a value of "Matcha". This will fix it.

**Comment by vinceliuice** [comment]
This is one solution to this issue, also we can add userChrome.css file for firfox to fix this, but the first solution is more easy solve this, I know the best way to fix it is add patch at gtk.css for firfox, but ｕnfortunately firfox does not support this. you can text other gtk themes, all dark version have this issue,  and we all have no better choice about this.
