### ISSUE TITLE
distorted icons in vertical panel (cinnamon)

### ISSUE THREAD

**Issue by mabod** [vinceliuice/matcha#68]
I am using Cinnamon desktop with Manjaro Testing.

Cinnamon has 3 different config options for themes:

![Bildschirmfoto vom 2019-06-09 15-22-03](https://user-images.githubusercontent.com/10911665/59159484-7dcb1980-8aca-11e9-91c1-c1bd6aa897bc.png)

If I select Matcha theme for the Desktop, the icons in my vertical panel are distorted. They are horizontally squeezed:

![Bildschirmfoto vom 2019-06-09 15-19-59](https://user-images.githubusercontent.com/10911665/59159495-a521e680-8aca-11e9-8031-dfaf6b4edcdb.png)

All other themes I have used (Adapta, Plata, Vertex, etc.) do not have that issue and show nice icons:

![Bildschirmfoto vom 2019-06-09 15-19-44](https://user-images.githubusercontent.com/10911665/59159511-e31f0a80-8aca-11e9-82b0-4f1b48b6043a.png)

I am using the following settings for the vertical panel:

![Bildschirmfoto vom 2019-06-09 15-27-08](https://user-images.githubusercontent.com/10911665/59159525-1b264d80-8acb-11e9-98ba-334fad7b6c54.png)

**Comment by vinceliuice** [comment]
Fixed now!
