### ISSUE TITLE
gtk2 theme not working

### ISSUE THREAD

**Issue by nergdron** [vinceliuice/matcha#7]
I'm running Ubuntu 17.10, and after installing the Matcha dir to ~/.local/share/themes, most of the themes work, but the gtk2 theme doesn't load correctly, I just get the oldschool "no theme" design in gtk2 apps. I've verified I've installed the gtk2 prereqs:

⟫ dpkg -l | grep gtk2-engines
ii  gtk2-engines:amd64                         1:2.20.2-3ubuntu1                                          amd64        theme engines for GTK+ 2.x
ii  gtk2-engines-murrine:amd64                 0.98.2-0ubuntu5                                            amd64        cairo-based gtk+-2.0 theme engine
ii  gtk2-engines-pixbuf:amd64                  2.24.31-2ubuntu1                                           amd64        pixbuf-based theme for GTK+ 2.x

Is there a better way to debug why it isn't loading?

**Comment by denikris** [comment]
it also happen with synaptic packages manager in lubuntu 17.10
![2018-03-15-213214_1024x600_scrot](https://user-images.githubusercontent.com/16707606/37469723-872d6504-2898-11e8-9863-deed405f7e2f.png)

**Comment by vinceliuice** [comment]
Themes are not installed in the system directory, then software that requires administrator authority cannot be used this theme (if you are just install at your user directory)

**Comment by vinceliuice** [comment]
To fix this, you should use root user or authority to install this theme
