### ISSUE TITLE
text displaced in cinnamon panel

### ISSUE THREAD

**Issue by mabod** [vinceliuice/matcha#71]
I am using matcha-gtk-theme 20190622-1 on Manjaro Stable with cinnamon 4.2.3. 

In my horizontal top panel the text of the window titles is displaced so that only half of it can be seen:

![Bildschirmfoto vom 2019-08-03 07-28-21](https://user-images.githubusercontent.com/10911665/62407949-e44b5000-b5c0-11e9-8bb1-b4d4ec60ca62.png)

While other themes like Adapta-Nokto-Maia display it fine:

![Bildschirmfoto vom 2019-08-03 07-28-35](https://user-images.githubusercontent.com/10911665/62407953-f3320280-b5c0-11e9-922a-05374cb6f434.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed
