### ISSUE TITLE
Release matcha-icon-theme

### ISSUE THREAD

**Issue by romildo** [vinceliuice/matcha#74]
The meta themes in this project [uses the **matcha icon theme**](https://github.com/vinceliuice/matcha/blob/master/Install#L58). Please, publish and release matcha icon theme on github, so that it can be packaged by distributions that already packages the matcha gtk theme, enabling a more complete theming experience.

**Comment by vinceliuice** [comment]
I use [Qogir-manjaro](https://github.com/vinceliuice/Qogir-icon-theme) for Matcha

**Comment by romildo** [comment]
Thanks for updating it.
