### ISSUE TITLE
Text almost unreadable in Mate task bar

### ISSUE THREAD

**Issue by romildo** [vinceliuice/matcha#76]
The text in the task bar of the Mate desktop environment is almost unreadable for inactive windows when using Matcha-sea or Matcha-light-sea themes. Both the background and foreground colors are dark.

![Screenshot from 2019-09-18 17-41-26](https://user-images.githubusercontent.com/1217934/65184833-bb7dfd80-da3c-11e9-8efe-466411dca4f4.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now!
