### ISSUE TITLE
Thunar sidebar also in light and normal variant dark

### ISSUE THREAD

**Issue by philmmanjaro** [vinceliuice/matcha#79]
It seems Thunar is styled similar to the dark variant also in light and normal version.

![Bildschirmfoto_2019-10-25_21-51-19](https://user-images.githubusercontent.com/5050022/67600224-ecef9480-f771-11e9-8250-77b27f91d76c.png)

This results in some icons of light variants not displaying correctly. Like gray in gray. It would be great to have Thunar sidebar not dark but normal styled.

Here a similar screenshot with Materia theme

![Bildschirmfoto_2019-10-25_21-55-42](https://user-images.githubusercontent.com/5050022/67600368-4f489500-f772-11e9-9fd9-ba7eaa62282c.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
It's ok!
