### ISSUE TITLE
Menubars broken in Xfce

### ISSUE THREAD

**Issue by thegrublord** [vinceliuice/matcha#8]
I've installed this theme through the Installer script, and when I open up thunar, the toolbar is white instead of black, giving it a jarring look. It has been working fine in xfce4-terminal and firefox however.
![screenshot_2017-11-29_21-46-58](https://user-images.githubusercontent.com/21349328/33416010-2fc31c4c-d54f-11e7-941e-f73afee807a4.png)

**Comment by vinceliuice** [comment]
Fixed now!
