### ISSUE TITLE
Chrome and VS Code menus aren't dark like other apps

### ISSUE THREAD

**Issue by waynebloss** [vinceliuice/matcha#81]
Using the `Matcha-dark-azul` theme in Manjaro, XFCE - most apps have a dark menu but not Chrome or VS Code.

Another theme that I used to use called `Adapta-Nokto-Eta-Maia` [1] from [adapta-gtk-theme](https://github.com/adapta-project/adapta-gtk-theme) got this right. However, that one is no longer maintained and no longer included by Manjaro by default.

I don't know anything about theming GTK or I'd send you a pull request. Sorry. Thanks for a really great theme though! I like it better than Adapta.

[1] [adapta-maia-theme PKGBUILD](https://github.com/oberon-manjaro/adapta-maia-theme/blob/master/PKGBUILD)

**Comment by vinceliuice** [comment]
I fixed this

**Comment by waynebloss** [comment]
Thank you!
